FROM rust:latest
LABEL maintainer="Sophie Tauchert <sophie@999eagle.moe>"

# Rust targets

RUN rustup target add x86_64-pc-windows-gnu 
RUN rustup toolchain install nightly

RUN rustup target add x86_64-pc-windows-gnu --toolchain nightly
# apt packages

RUN apt-get update && \
	apt-get -y install mingw-w64 clang llvm-dev libxml2-dev uuid-dev libssl-dev bash patch make tar xz-utils bzip2 gzip sed cpio && \
	apt-get clean

# Windows compiler

RUN ln -s windows.h /usr/x86_64-w64-mingw32/include/Windows.h && \
	ln -s shlobj.h /usr/x86_64-w64-mingw32/include/Shlobj.h

